version: '3.3'
services:
  database:
    container_name: projectname_db
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=your-database-name
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./docker/mongoinit/init-mogo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./docker/database:/data/db

  mongo-express:
    container_name: projectname_mongoexpress
    image: mongo-express:latest
    restart: always
    ports:
      - 8086:8081
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret

  php:
    build: ./docker/php-fpm
    container_name: projectname_php
    depends_on:
      - database
    environment:
      - TIMEZONE="Europe/Paris"
      - APP_ENV=dev
      - MONGO_HOST=mongodb://localhost:27017
      - MONGO_DB=your-database-name
    ports:
      - "9000:9001"
    volumes:
      - .:/var/www/app:cached

  nginx:
    build: ./docker/nginx
    container_name: projectname_nginx
    depends_on:
      - php
    ports:
      - "81:80"
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - .:/var/www/app:cached
